### ISSUE TITLE
string literals, quotes bug

### ISSUE THREAD

**Issue by tunnckoCore** [jonschlinkert/strip-comments#12]
As we comment with @mk-pmb at https://github.com/tunnckoCore/strip-comments/pull/3

Check this [test](https://github.com/jonschlinkert/strip-comments/blob/latest%2Bquotes_bug/test/test.js#L30-35) and the [fixture](https://github.com/jonschlinkert/strip-comments/blob/latest%2Bquotes_bug/test/fixtures/no-comments.js) for it.

The new branch `latest+quotes_bug` shows the problem and inherits from `cli` branch

**Comment by jonschlinkert** [comment]
fixed
