### ISSUE TITLE
globs bug

### ISSUE THREAD

**Issue by jonschlinkert** [jonschlinkert/strip-comments#14]
Sometime in the last couple of commits a bug was introduced. it freezes on these patterns:

```js
verb.data('data/*.yml');
verb.includes('includes/*.md');
verb.docs('docs/*.md');
```

**Comment by tomByrer** [comment]
Would [this parser](https://github.com/cr0cK/gulp-lightmin/blob/master/index.js#L34-L119) help pass tests, while not being as heavy as esprima?

**Comment by jonschlinkert** [comment]
going the parsing route might not be a bad idea. the regex if fun, and the reason I used it was to keep this light and simple, but a million edge cases always pop up that make the regex need to be tweaked.  doing the parsing isn't a problem (https://github.com/jonschlinkert/parse-comments, https://github.com/jonschlinkert/parse-blocks/blob/master/index.js, https://github.com/jonschlinkert/extract-comments/blob/master/lib/extract.js, https://github.com/jonschlinkert/js-comments).

**Comment by jonschlinkert** [comment]
fixed
