### ISSUE TITLE
Hangs when comment-like string not closed

### ISSUE THREAD

**Issue by turadg** [jonschlinkert/strip-comments#18]
When I call strip comments on a file containing a line such as this:
```javascript
          if (accept == 'video/*') {
```

…it never returns.

**Comment by jonschlinkert** [comment]
thanks for reporting this

**Comment by blake-jennings** [comment]
Having the same issue - throws an "Unterminated group" error.

**Comment by tunnckoCore** [comment]
yep currently have some bug and we have few more libs for that lol :D 

https://github.com/jonschlinkert/esprima-extract-comments
https://github.com/jonschlinkert/extract-comments
https://github.com/jonschlinkert/parse-comments
https://github.com/jonschlinkert/js-comments

or try that https://github.com/tunnckoCore/code-comments-regex (not published) 
or code from that https://github.com/jonschlinkert/extract-comments/issues/1#issuecomment-102374719
