### ISSUE TITLE
'use stric' error, should be 'use strict'

### ISSUE THREAD

**Issue by bjarte-johansen** [jonschlinkert/strip-comments#19]
https://github.com/jonschlinkert/strip-comments/blob/master/index.js

you have written 'use stric' instead of 'use strict' which means it will not be parsed in strict mode at all

**Comment by jonschlinkert** [comment]
> which means it will not be parsed in strict mode at all

Well that's why I made the typo, to prevent it from being parsed in strict mode. jk ;)

@tunnckoCore I thought that was fixed a loooooooong time ago? wasn't it?

**Comment by tunnckoCore** [comment]
hmmmm... I dont know, actually. Cuz badge shows it is 0.3.2, in commits history there's no 0.3.2 commit. Also cant remember what we decide finally.

**Comment by tunnckoCore** [comment]
We also have some PRs and I came with that solution. https://github.com/tunnckoCore/code-comments-regex

**Comment by jonschlinkert** [comment]
fixed
