### ISSUE TITLE
check this code

### ISSUE THREAD

**Issue by coolbong** [jonschlinkert/strip-comments#20]
This code still remains comments

void method() 
{//method start

}//method end

**Comment by tunnckoCore** [comment]
@coolbong hi, thanks for the report.
It's strange, but yea, understandable cuz currently lib have some bugs and is a lil' bit freezed, imo.

**Comment by tunnckoCore** [comment]
@coolbong try this https://github.com/tunnckoCore/acorn-strip-comments

**Comment by jonschlinkert** [comment]
@coolbong thanks I'll look into it. I've planned on changing this to a non-regex solution for a while because of these edge cases

**Comment by tunnckoCore** [comment]
> I've planned on changing this to a non-regex solution for a while because of these edge cases

we have it as `acorn-strip-comments` and `acorn-extract-comments` :) but okey it's yours :+1:

**Comment by jonschlinkert** [comment]
and we have it as esprima-extract-comments :) which was done last year

**Comment by jonschlinkert** [comment]
https://github.com/jonschlinkert/esprima-extract-comments.

**Comment by tunnckoCore** [comment]
> and we have it as esprima-extract-comments :) which was done last year

yea just forgot it and popped up in my mind few mins after my comment.

**Comment by jonschlinkert** [comment]
should be fixed in the latest release
