### ISSUE TITLE
Keep newlines

### ISSUE THREAD

**Issue by lebbe** [jonschlinkert/strip-comments#24]
Thanks for this cool project. I do have a feature request.

What would be very handy is if we could keep the new-lines when stripping comments, so that the line numbers in the code we serve along with the sourcemaps matches the original source code. This is indeed not a big issue, but a small feature that would make my life feel somewhat more fulfilled.

In our use-case, we strip comments and distribute the js-files along with minified code and sourcemaps. This is, of course, because we can feel freer in our comment-writing knowing the comments are not available for the outside world. The reason we ship the original code along with the minified code is of course because it is a lot more easier to debug.

**Comment by jonschlinkert** [comment]
sounds like a good idea. would you want to do a pr? or I can look at implementing next time I make changes.

**Comment by lebbe** [comment]
I'll see if I find the time this weekend.

**Comment by jonschlinkert** [comment]
closed by https://github.com/jonschlinkert/strip-comments/commit/1c31f598e453ddb71ec725add59df0419ea3cb54.

Thank you! sorry for the delay
