### ISSUE TITLE
0.3.x branch: Empty line comments strip the next line

### ISSUE THREAD

**Issue by epicoxymoron** [jonschlinkert/strip-comments#26]
In [the line comment regex](https://github.com/jonschlinkert/strip-comments/blob/0.3.4/index.js#L12), it matches "//" followed by some content.  If the code is

```javascript
//
// Stuff to do
//
code();
moreCode();
```

... then the final `//` drags `code()` out of the output as well.  A simplified example you can run in the console:

```javascript
console.log('//\ncode();\nmoreCode();'.replace(/(^|[^\S\n])(?:\/\/)([\s\S]+?)$/gm, ''));
```

Outputs:
```javascript

moreCode();
```

My first instinct was changing the regex as a whole to a more simple `/\/\/.*$/`, but that obviously creates a regression within strings...

Then I thought, what if we replaced `(?:\/\/)([\s\S]+?)$` with `(?:\/\/)([\s\S]*?)$`?  The remaining tests pass, and in the console:

```javascript
console.log('//\ncode();\nmoreCode();'.replace(/(^|[^\S\n])(?:\/\/)([\s\S]*?)$/gm, ''));
```

Outputs:
```javascript

code();
moreCode();
```

For what it's worth, the relevant test added in #12 fails for me both before and after the suggested change, with the `0.3.4` tag checked out.

**Comment by jonschlinkert** [comment]
Sorry 0.3.x will no longer be supported. I moved away from regex because of these types of problems.
