### ISSUE TITLE
0.4.x branch: discard() is too greedy

### ISSUE THREAD

**Issue by epicoxymoron** [jonschlinkert/strip-comments#27]
Test case:

```javascript
//
// foo
var x = 1;
```

`extract-comments` correctly identifies the comments (sorry for that red herring), but the replacement approach of `split/join` does too much.

In the example above, as the first comment is being removed, it also chops off the "//" from the beginning of line 2.  As the second comment is being removed, `// foo` is no longer in the string, so it's not replaced.  In the end, the output is

```javascript
 foo
var x = 1;
```

Essentially, any comment which is itself a substring of a later comment causes the stripping of the later comment to fail.

The good news is that a simple `return str.replace(comment.raw, '');` should do the trick **if and only if** the comments are processed in source-code order.  If they're not, I think your existing split/join approach would probably be fine if you sorted the comments by length before processing them

**Comment by jonschlinkert** [comment]
Would you want to create a pull request? or I can fix next time I make changes. 

thanks for creating and the issue and looking into it. I had a cold most of last week, so I'm a little behind. I'll try to look into this if someone else doesn't beat me to it

**Comment by epicoxymoron** [comment]
I'll probably have some time to get a PR going on Thursday evening.  Hope you're feeling better!

**Comment by jonschlinkert** [comment]
Great thanks!
