### ISSUE TITLE
Escaped forward-slash being parsed as if it's a forward-slash

### ISSUE THREAD

**Issue by Tim-Thomas** [jonschlinkert/strip-comments#29]
This error was introduced with the rewrite in 0.4.1.

\> strip('"foo/bar".replace(/o\//,"g")')
'"foo/bar".replace(/o'
\> "foo/bar".replace(/o\//,"g")
'fogbar'
\> strip('"foo/bar".replace(/\//,"g")')
'"foo/bar".replace('
\> "foo/bar".replace(/\//,"g")
'foogbar'

When this is fixed, I suspect it's also worth adding this to test cases. I may try to see if I can figure out what's causing this.

**Comment by Tim-Thomas** [comment]
Looks like this is ultimately an issue in extract-comments. Opening a related ticket there.

**Comment by jonschlinkert** [comment]
Thanks, closing here so we can continue over on https://github.com/jonschlinkert/extract-comments/issues/12
