### ISSUE TITLE
How was it tested?

### ISSUE THREAD

**Issue by vitaly-t** [jonschlinkert/strip-comments#30]
If I try giving it a file that I want stripped off comments, I'm not getting anything expected back.

Try to use file [Angular JS 1.5 Core](https://code.angularjs.org/1.5.0-rc.0/angular.js) as an input, and see what result you will get back.

For me it just doesn't work.

Here's my test:
```js
var strip = require('strip-comments');
var fs = require('fs');

fs.readFile('input.js', 'utf8', function (err, data) {
    if (err) {
        return console.log(err);
    }
    var start = new Date().getTime();
    var result = strip(data);
    var end = new Date().getTime();
    console.log("Time:", end - start);
    fs.writeFile('output.js', result);
});
```
It expects the input from the local `input.js` file, then processes it for about 4 seconds, and then produces file `output.js` that looks nothing like what was expected.

**Comment by jonschlinkert** [comment]
Sounds like an infinite loop is happening somewhere. I'll look into it.

what version are you using?

**Comment by vitaly-t** [comment]
I was using the very latest version. And as stated, it finished after 4 seconds, it didn't go into an infinite loop.

**Comment by jonschlinkert** [comment]
> as stated, it finished after 4 seconds, it didn't go into an infinite loop.

Ok, then it took 4 seconds for reasons completely unrelated to this library - like you're processing a few million lines of code, or doing something else that is causing it to take that long. Which means that there is the possibility that something else is mangling the result, like a minifier. 

> looks nothing like what was expected.

This is vague. Could you describe what you expect? Ideally you could paste a snippet of before/after to show what's happening

**Comment by jonschlinkert** [comment]
Also, how was **what** tested?  are you asking about [unit tests](https://github.com/jonschlinkert/strip-comments/blob/master/test/test.js) (and [these](https://github.com/jonschlinkert/extract-comments/blob/master/test/test.js)).

If the heading of this issue accurately reflects the problem you're experiencing, then let's close, since it's now answered.

**Comment by vitaly-t** [comment]
For starters, the library did not remove any comments. I haven't looked at what else id did, if anything, because if comments aren't removed, the rest is irrelevant.

**Comment by jonschlinkert** [comment]
> And you misunderstood, I didn't care how long it took to process the given 30,000 lines of code (not millions), I only care about the output result.

Sorry, you misunderstand again. This is fast, much faster than something that would take 4 seconds on anything that isn't either huge, or there is a bug causing it to take 4 seconds. It should take maybe a few milliseconds on a few files with ~1k sloc. 

> I haven't looked at what else it did, if anything, because if comments aren't removed, the rest is irrelevant.

Ok, closing. If you are unwilling to help in the debugging process, I have to assume it's something you're doing wrong or something that we'll only find when someone else has the same issue and is willing to provide more information.

**Comment by vitaly-t** [comment]
>If you are unwilling to help in the debugging process.

That was quickly concluded without me saying anything on the matter. Fair enough.
