### ISSUE TITLE
No multi-line comment support?

### ISSUE THREAD

**Issue by vitaly-t** [jonschlinkert/strip-comments#32]
Trying  a simple example:

``` js
/*
 test comments
 */
Hey!
```

The same comes out, no comments removed.

**Comment by jonschlinkert** [comment]
esprima is used for comment matching/extraction.  strange, it seems like that should be supported. I can look into it

**Comment by vitaly-t** [comment]
Yeah, I don't know what is going on there... but I've just looked through it, and the pattern isn't very good...

Your library uses [extract-comments](https://github.com/jonschlinkert/extract-comments), which then uses [esprima-extract-comments](https://github.com/jonschlinkert/esprima-extract-comments), which then uses [esprima](https://github.com/jquery/esprima) to parse the code to extract the comments.... that is such an overkill...

The weakest link of this all is the use of [esprima-extract-comments](https://github.com/jonschlinkert/esprima-extract-comments), because it parses the code.

Parsing the code for a task such as finding comments or other elements is not needed. For that purpose esprima implements tokenatization that can be used separately. Tokenizing code will give you all the information needed, except it is 10 times faster and that much lighter on memory usage.

You should be using esprima directly, with its `tokenize` method, not `parse` method.

**Comment by jonschlinkert** [comment]
I just refactored to use esprima, I don't know their API very well.

> you should be using esprima directly, with its tokenize method, not parse method.

 I'll look into tokenize, is that documented somewhere?

**Comment by vitaly-t** [comment]
I gave you an example in that link how it works with enumerating the regular expressions. With comment blocks it works the same way, just switch the object's type.

```js
function parseRegEx(originalCode) {
    var result = [];
    esprima.tokenize(originalCode, {loc: true, range: true}, function (obj) {
        if (obj.type === 'RegularExpression') {
            result.push({
                startIdx: obj.range[0],
                endIdx: obj.range[1]
            });
        }
    });
    return result;
}
```

**Comment by jonschlinkert** [comment]
> I gave you an example in that link how it works with enumerating the regular expressions.

Yes, thanks for that, but you implied that this is a "known" way to use esprima. want to do a pr?

**Comment by vitaly-t** [comment]
I'm not familiar with your library enough to do a PR. And I gave you as much information about esprima as I knew. It's up to you now what to do with it ;)

**Comment by jonschlinkert** [comment]
looks like you have a lib that strips comments. is it not working?

**Comment by vitaly-t** [comment]
It is working fine, though I wrote it after I found yours. I did a lot of research for the best way to handle regular expressions, and the link I gave you was my post on the subject. My library works differently though, it was written to handle all types of files that use comments `//`, `/**/` and `<!-- -->`, that's why implementation is very different from yours also. However, one thing they share - getting the best of esprima - that's where method `tokenize` comes from. You can see it used in my library here: https://github.com/vitaly-t/decomment/blob/master/lib/utils.js

I too first relied on method `parse` till Ariya Hidayat came along (the author of esprima), and suggested that I should absolutely switch to `tokenize`.
