### ISSUE TITLE
outdated version dependency?

### ISSUE THREAD

**Issue by andreashuetter** [jonschlinkert/strip-comments#33]
Hi Jon, is there a certain reason why strip-comments is still depending on the outdated version 0.8.7 of extract-comments? Can we just update this in the package.json file from 

  "dependencies": {
    "extract-comments": "^0.8.7"

to

  "dependencies": {
    "extract-comments": "^0.10.1"

?

**Comment by tunnckoCore** [comment]
hi @andreashuetter 

I don't think so. I'll try to bump and if no breaking changes it would be ready for publish by @jonschlinkert, cuz i don't have npm rights.

**Comment by tunnckoCore** [comment]
The only breaking change would be that it no longer can strip comments from json, because using `esprima` under the hood. But that's not so big pain, imho? @jonschlinkert thoughs?

I can PR with changes.
