### ISSUE TITLE
The project description is misleading

### ISSUE THREAD

**Issue by NindroidX** [jonschlinkert/strip-comments#38]
The description says the following:

> The tests remove comments from JavaScript, but this will work with any language that uses the same syntax for comments.

I wanted to use this package to remove JSDoc style comments from a .scss file (used for generating a styleguide), but it does not work (throws Unexpected token errors). I'm guessing esprisma chokes on the .scss syntax.

Anyway, I think the description should be changed, as this is not that easily fixable (because of the esprisma dependancy)?

For people looking for a library that can remove comments from other type of files: https://github.com/vitaly-t/decomment

**Comment by jonschlinkert** [comment]
meaning the one on GitHub above the project? Fixed.
